"""Add shared_post_id

Revision ID: 30e9fb5834fa
Revises: ce0b4b8930dc
Create Date: 2026-03-19 09:38:23.087908
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '30e9fb5834fa'
down_revision: Union[str, None] = 'ce0b4b8930dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('shared_post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'posts', ['shared_post_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'shared_post_id')
    # ### end Alembic commands ###
