"""Add profile images

Revision ID: ce0b4b8930dc
Revises: 20260318_0002
Create Date: 2026-03-19 09:22:44.464361
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ce0b4b8930dc'
down_revision: Union[str, None] = '20260318_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_media_interaction', 'reel_interactions', type_='unique')
    op.drop_constraint('reel_interactions_media_id_fkey', 'reel_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'reel_interactions', 'post_media', ['media_id'], ['id'])
    op.drop_constraint('reel_views_media_id_fkey', 'reel_views', type_='foreignkey')
    op.create_foreign_key(None, 'reel_views', 'post_media', ['media_id'], ['id'])
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('cover_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_url')
    op.drop_column('users', 'avatar_url')
    op.drop_constraint(None, 'reel_views', type_='foreignkey')
    op.create_foreign_key('reel_views_media_id_fkey', 'reel_views', 'post_media', ['media_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'reel_interactions', type_='foreignkey')
    op.create_foreign_key('reel_interactions_media_id_fkey', 'reel_interactions', 'post_media', ['media_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uix_user_media_interaction', 'reel_interactions', ['user_id', 'media_id', 'interaction_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
