"""Add is_private to Post

Revision ID: f660ed3b5678
Revises: 30e9fb5834fa
Create Date: 2026-03-19 09:49:37.163137
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'f660ed3b5678'
down_revision: Union[str, None] = '30e9fb5834fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_private')
    # ### end Alembic commands ###
