"""add otp_verification table

Revision ID: f75ad09b8f2a
Revises: 20260320_0001
Create Date: 2026-03-24 13:55:07.040282
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'f75ad09b8f2a'
down_revision: Union[str, None] = '20260320_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index('uq_posts_confession_number', table_name='posts')
    op.create_unique_constraint(None, 'posts', ['confession_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.create_index('uq_posts_confession_number', 'posts', ['confession_number'], unique=False)
    op.alter_column('posts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
